# Only contains stuff necessary for the "grid" to function.
# Your bashrc should call this one.

# User specific aliases and functions
export GRID_HOME=/home/dkwasny/GridStuff;
export JAVA_HOME=/home/dkwasny/Utilities/jdk1.7.0_45;

export HADOOP_COMMON_HOME=/home/dkwasny/Utilities/hadoop-2.2.0;
export HADOOP_HDFS_HOME=$HADOOP_COMMON_HOME;
export HADOOP_MAPRED_HOME=$HADOOP_COMMON_HOME;
export HADOOP_YARN_HOME=$HADOOP_COMMON_HOME;
export HADOOP_CONF_DIR=$GRID_HOME/conf;
export YARN_CONF_DIR=$HADOOP_CONF_DIR;

export ZOOKEEPER_HOME=/home/dkwasny/Utilities/zookeeper-3.4.5;
export ZOO_LOG_DIR=$ZOOKEEPER_HOME/logs

PATH=/home/dkwasny/Utilities/clang/bin:$PATH;
PATH=$JAVA_HOME/bin:$PATH;
PATH=$HADOOP_COMMON_HOME/bin:$PATH;

alias grid-start="$GRID_HOME/scripts/grid-toggle.sh start";
alias grid-stop="$GRID_HOME/scripts/grid-toggle.sh stop";
alias grid-restart="grid-stop; grid-start";
alias update-grid-homes="$GRID_HOME/scripts/update-grid-homes.sh";
