# Only contains stuff necessary for the "grid" to function.
# Your bashrc should call this one.

# User specific aliases and functions
export GRID_HOME=/home/dkwasny/GridStuff;
export JAVA_HOME=/home/dkwasny/Utilities/jdk1.7.0_45;

export HADOOP_COMMON_HOME=/home/dkwasny/Utilities/hadoop-2.2.0;
export HADOOP_HDFS_HOME=$HADOOP_COMMON_HOME;
export HADOOP_MAPRED_HOME=$HADOOP_COMMON_HOME;
export HADOOP_YARN_HOME=$HADOOP_COMMON_HOME;
export HADOOP_CONF_DIR=$GRID_HOME/conf;
export YARN_CONF_DIR=$HADOOP_CONF_DIR;

export HBASE_HOME=/home/dkwasny/Utilities/hbase-0.96.0-hadoop2;
export HBASE_CONF_DIR=$HADOOP_CONF_DIR;

export ZOOKEEPER_HOME=/home/dkwasny/Utilities/zookeeper-3.4.5;
export ZOO_LOG_DIR=$ZOOKEEPER_HOME/logs

export CATALINA_HOME=/home/dkwasny/Utilities/apache-tomcat-8.0.5;

PATH=$JAVA_HOME/bin:$PATH;
PATH=$HADOOP_COMMON_HOME/bin:$PATH;
PATH=$HBASE_HOME/bin:$PATH;

alias hadoop-start="$GRID_HOME/scripts/hadoop-toggle.sh start";
alias hadoop-stop="$GRID_HOME/scripts/hadoop-toggle.sh stop";
alias zookeeper-start="$GRID_HOME/scripts/zookeeper-toggle.sh start";
alias zookeeper-stop="$GRID_HOME/scripts/zookeeper-toggle.sh stop";
alias hbase-start="$GRID_HOME/scripts/hbase-toggle.sh start";
alias hbase-stop="$GRID_HOME/scripts/hbase-toggle.sh stop";

alias tomcat-start="$CATALINA_HOME/bin/startup.sh";
alias tomcat-stop="$CATALINA_HOME/bin/shutdown.sh";
alias tomcat-restart="tomcat-stop; tomcat-start"
alias tomcat-grid-toggle="$GRID_HOME/scripts/tomcat-grid-toggle.sh";

alias grid-start="hadoop-start; zookeeper-start; hbase-start";
alias grid-stop="hbase-stop; zookeeper-stop; hadoop-stop";
alias grid-restart="grid-stop; grid-start";

alias update-grid-homes="$GRID_HOME/scripts/update-grid-homes.sh";
